export const paths = {
  home: 'home',
  login: 'login',
  shopGrid: 'shop-grid-cart',
  aboutUs: 'about-us',
  accountInfo: 'account-info',
  cart: 'cart',
  checkout: 'checkout',
  compareItem: 'compare-product',
  contact: 'contact',
  errorPage: 'error-page',
  favorite: 'favorite',
  forgotPass: 'forgot-password',
  privacyPolicy: 'privacy-policy',
  productDetail : 'product-detail',
  purchaseGuide: 'purchase-guide',
  register: 'register',
  resetPass: 'reset-password',
  shopFilter : 'shop-filter',
  term: 'term',
  invoice: 'invoice',
  allProducts: 'allProducts'
}
